In [1]:
import numpy as np

In [7]:
n = np.array([0, 0, 1, 2, 3, 2, 1, 0, 0])
c = n + np.roll(n, 1) 
c



array([0, 0, 1, 3, 5, 5, 3, 1, 0])

In [30]:
""" dc/dt = n(t) - n(t-2)"""
size = len(n)
D = np.diag([1]*size, k=0) 
for i in range(size):
    D[(i+2)%size, i] = -1
D

array([[ 1,  0,  0,  0,  0,  0,  0, -1,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0, -1],
       [-1,  0,  1,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  0,  1,  0,  0,  0,  0,  0],
       [ 0,  0, -1,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  1,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0, -1,  0,  1]])

In [29]:
n_pseudo = np.linalg.pinv(D)@c
n_predict = n_pseudo #- min(n_pseudo)
n_predict

array([-1.00000000e+00, -1.66666667e+00, -1.33333333e+00,  4.44089210e-16,
        1.33333333e+00,  1.66666667e+00,  1.00000000e+00,  3.33333333e-01,
       -3.33333333e-01])

In [37]:
T = np.array([[1, 0, -1], [-1, 1, 0], [0, -1, 1]])
print( T@np.array([10, 0, 0]) )
np.linalg.pinv(T)@np.array([10, -10, 0])

[ 10 -10   0]


array([ 6.66666667, -3.33333333, -3.33333333])

In [38]:
np.linalg.lstsq(D, c)

C:\Users\schaekente\AppData\Local\Temp\ipykernel_2808\2467982131.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(D, c)


(array([-1.0000000e+00, -2.0000000e+00, -2.0000000e+00, -1.0000000e+00,
         1.0000000e+00,  2.0000000e+00,  2.0000000e+00,  1.0000000e+00,
        -7.3511423e-16]),
 array([], dtype=float64),
 8,
 array([1.96961551e+00, 1.96961551e+00, 1.73205081e+00, 1.73205081e+00,
        1.28557522e+00, 1.28557522e+00, 6.84040287e-01, 6.84040287e-01,
        8.46725286e-17]))

In [59]:
n = np.array([0, 1, 1, 2, 3, 2, 1, 0, 0])
dc = n - np.roll(n, 2) 
c = np.cumsum(dc)
c


array([0, 1, 2, 3, 5, 5, 3, 1, 0], dtype=int32)

In [44]:
size = len(n)
D = np.diag([1]*size, k=0) 
for i in range(size):
    D[(i+2)%size, i] = -1
D
n_pseudo = np.linalg.pinv(D)@c
n_pseudo

array([-1.00000000e+00, -1.00000000e+00, -2.00000000e+00, -1.00000000e+00,
        6.10622664e-16,  1.00000000e+00,  2.00000000e+00,  1.00000000e+00,
        1.00000000e+00])

In [60]:
from scipy.optimize import least_squares

def optimize_func(x):
    dc = x - np.roll(x, 2) 
    c_predict = np.cumsum(dc)
    return c_predict - c

size = len(n)
x0 = np.array([0]*size)

res_1 = least_squares(optimize_func, x0)
res_1.x

array([-1.132989  , -0.13298901, -0.132989  ,  0.867011  ,  1.86701099,
        0.867011  , -0.13298901, -1.132989  , -1.13298901])